server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /user/**, /booking/**
        - id: hotel
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**, /api/rooms/**
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:devsecret}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/